apiVersion: v1
kind: Service
metadata:
  name: passwordapi
  labels:
    name: passwordapi
spec:
   selector:
     name: passwordapi
   ports:
     - protocol: TCP
       port: 8080
       nodePort: 32080
   type: NodePort
